### PR TITLE
Follow Curios' canEquip intended purpose

### LINKED ISSUE #159: Mild incompatibility with The Endergetic Expansion
#### Versions:
 * EnigmaticLegacy-2.11.1
 * curios-forge-1.16.5-4.0.5.0
 * Patchouli-1.16.4-50
 * abnormals_core-1.16.5-3.1.1 (not the issue, this library installed is just fine)
 * endergetic-1.16.4-3.0.0
 * forge 36.0.43

#### Description:
Mild incompatibility with The Endergetic Expansion Mod: https://www.curseforge.com/minecraft/mc-mods/endergetic

All equipped curios added by Enigmatic Legacy are unequipped when quitting and reentering singleplayer or server worlds. If there's no inventory space available the curios will be dropped onto the ground.

The unequipped curios will leave a ghost item in the curios slot that dissapears when it is interacted with.

It only affects Enigmatic Legacy's curios, and more importantly, affects the seven curses ring, so it's possible to get it off without the power of god.

#### How to Reproduce:
1. Load a world
2. Equip any Enigmatic curios, including the ring of seven curses
3. Log out/save and quit
4. Reenter the world
5. Behold!
image

#### Logs:
No crashes.

Should I post an issue on the other mod's repository?

### LINKED ISSUE #160: Curio items invalidated then ejected into player inventory
**Forge:** 1.16.5-36.0.44
**Patchouli:** 1.16.4-50
**Curios:** 1.16.5-4.0.5.0
**Enigmatic Legacy:** 2.11.1

**Issue:** Curio items are ejected from slots and placed in inventory upon reload of a world.

**How to reproduce:** Have Curios version 4.0.5.0, load a world, put item in Curio slot. Reload world.

This is a new feature from Curios. According to the author, this happens when a Curio is invalidated or has modified tags in your inventory. This normally isn't much of a problem unless your inventory is full, to which the item will dissappear.

### PR DESCRIPTION
**Pull request by wchen1990**
- Addresses #159, #160

### CODE REVIEW

**Review by Aizistral — CHANGES_REQUESTED** [review]
That check was not in place for no reason, man. We have to prevent player from equipping multiple instances of the same accessory, because none of the accessories in the mod are designed to support such behavior.

Edit: just re-checked to see if Curios doesn't do that by default or something, as I had an impression it might be possible.

**Comment by wchen1990** [comment]
Yea, I just thought about that after I pushed it. I already have an idea of
how to go about it, but it might be a bit hacky. I'll get to it when I get
the chance.

**Comment by Aizistral** [comment]
It's actually rather simple to handle, we just need to check whether or not the `ItemStack` passed into c`anEquip` method is already among player's equipped curios'. From there we shall know whether to perform no-duplicate check or not.

**Comment by wchen1990** [comment]
That makes sense. I'll get back to you with the changes once I wake up.

**Review by Aizistral — APPROVED** [review]
Now looks good enough to me.

**Pull request merged**
