### PR TITLE
Astral breaker flames toggle

### LINKED ISSUE #147: Configurable Astral Breaker's particles
I feel the Astral Breaker's particles block vision.
I hope this can be configured on the client side.

### PR DESCRIPTION
**Pull request by pbone64**
Adds a config option to disable the flame particles created when the Astral Breaker mines a block

### CODE REVIEW

**Review by Aizistral — CHANGES_REQUESTED** [review]
Ideally such option should reside in the client config. You can see an example of how client-sided config options for items are implemented over here: https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/1.16.X/src/main/java/com/integral/enigmaticlegacy/items/MagmaHeart.java#L39-L74

**Comment by pbone64** [comment]
My bad, I'll change that right away.

**Comment by pbone64** [comment]
Fixed. Let me know if I mixed something required for the client-sided goodness.

**Comment by Aizistral** [comment]
Almost does it. But since server doesn't (and must not) know about client's client configs, it will be sending that packet anyways. You need to make sure you actually prevent particles from spawning on the proper side - that is, in packet handler: https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/1.16.X/src/main/java/com/integral/enigmaticlegacy/packets/clients/PacketFlameParticles.java#L48

**Comment by pbone64** [comment]
Argh, sorry about that, I'm new to mc netcode. I've pushed a fix, thanks for being patient.

**Review by Aizistral — APPROVED** [review]

**Pull request merged**
