### PR TITLE
Updated Sharpshooter to work with custom crossbows

### LINKED ISSUE #280: Sharpshooter overrides damage of modded crossbows
#### Versions:
 * Enigmatic Legacy: 2.16.1
 * Curios API: 5.0.6.1
 * Patchouli: 1.18.1-65
 * Forge: 39.0.66

#### Description of a Bug:
Sharpshooter is incompatible with modded crossbows as it overrides the damage of the arrow.
Any type of crossbow enchanted with sharpshooter always has the same damage no matter the original damage of the crossbow.

Example mod: Crossbowverhaul-1.2.4 enchanting the netherite crossbow with sharpshooter V decreases damage to exactly the same as normal crossbow with sharpshooter V.

Not exactly a bug but still annoying behaviour.

### PR DESCRIPTION
**Pull request by Flynatol**

### CODE REVIEW

**Comment by Aizistral** [comment]
Would it have been all that simple. The reason I have not done a fix myself as part of today's update is because any sort of  simple workaround for it defies the primary design of this enchantment - more specifically, a part where it makes crossbow damage fixed rather than randomly somewhere within upper and lower bound. While this is easily achievable with vanilla crossbow since we know the bounds for it, things are not quite as simple with modded ones, as there is no single "gimme your average damage or something" method.

I am still thinking on how to alter the design of Sharpshooter to alleviate this issue. Suggestions in this direction are open, but I would advise to present yours in #suggestions channel on my [Discord server](https://discord.gg/fuWK8ns) first before making a PR with implementation.

**Comment by Flynatol** [comment]
Oh I'll have a look at the discord thanks. But this workaround does actually fix the damage like the previous version, I've done it by computing the fixed damage based on the velocity and the base damage when shot and using that instead of the value 6 in the original calculation. All the sharpshooter levels are functionally identical to how they were before.

**Comment by Aizistral** [comment]
Perhaps. But your implementation holds on an assumption that base damage of the arrow will always be 2 for vanilla crossbows, and different (but still fixed) for modded ones. How do we guarantee that all modded crossbows will alter base damage of the arrow to achieve increased damage, and not do it some other way? How to be sure that they will set that base damage to exactly the same value every time, instead of it being randomized as well?

**Comment by Flynatol** [comment]
You're right, we can't guarantee that all modded crossbows will be fixed so the name of this PR should actually be more like "increased compatibility with modded crossbows". That being said this implementation works with all crossbows that use the vanilla way of increasing damage (increasing base damage and projectile velocity). Without seeing each implementation it is impossible to guarantee that sharpshooter will work well with all modded crossbows but this patch is an upgrade over the current system and will probably make it compatible with more mods than it is now.

**Comment by Aizistral** [comment]
Fine. Alright, I'll merge this for now, in case better solution will continue to elude me.

**Pull request merged**
