### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by FierceManul**
Add Simplified Chinese translation.
Translation progress : 60%

### CODE REVIEW

**Comment by Extegral** [comment]
Hey, that's pretty good.

I would assume you are already aware you should do this, but just in case: do you check out whether text alings properly in tooltips and is properly distributed within The Acknowledgment entries in-game?

**Review by Aizistral — COMMENTED** [review]
Hey, that's pretty good.

I would assume you are already aware you should do this, but just in case: do you check out whether text alings properly in tooltips and is properly distributed within The Acknowledgment entries in-game?

**Comment by FierceManul** [comment]
Yes, I checked.

**Comment by Aizistral** [comment]
Any plans to get done with remaining 40%?

**Comment by FierceManul** [comment]
I can if I have time, but I'm busy now.

**Review by Aizistral — APPROVED** [review]

**Pull request merged**
